#!/bin/bash

ls -l;

mv 'Andrew Scrivens.jpg' 'andrew-scrivens.jpg'
mv 'Andy Richens.png' 'andy-richens.png'
mv 'Ashveeta Singh Harripersadh.jpg' 'ashveeta-singh-harripersadh.jpg'
mv 'Barrie Hamilton.png' 'barrie-hamilton.png'
mv 'Caroline Lamyman.jpg' 'caroline-lamyman.jpg'
mv 'Ceri Pickering.jpg' 'ceri-pickering.jpg'
mv 'Christina Alexandrou.jpg' 'christina-alexandrou.jpg'
mv 'Colin Walker.jpg' 'colin-walker.jpg'
mv 'Dan Martin.png' 'dan-martin.png'
mv 'Dave Rowley_1.png' 'dave-rowley.png'
mv 'David Kirk.jpg' 'david-kirk.jpg'
mv 'David Pett.jpg' 'david-pett.jpg'
mv 'David Ramsdale.jpg' 'david-ramsdale.jpg'
mv 'Diane Wright.jpg' 'diane-wright.jpg'
mv 'Farhat Khan.png' 'farhat-khan.png'
mv 'Farzana Beg.jpg' 'farzana-beg.jpg'
mv 'Hilary Bevan.jpg' 'hilary-bevan.jpg'
mv 'Howard Royse.jpg' 'howard-royse.jpg'
mv 'James Butterworth.jpg' 'james-butterworth.jpg'
mv 'James Eason.jpg' 'james-eason.jpg'
mv 'John Endacott.jpg' 'john-endacott.jpg'
mv 'John Feaster.jpg' 'john-feaster.jpg'
mv 'John Woolley.jpg' 'john-woolley.jpg'
mv 'Jonathan Schwarz.jpg' 'jonathan-schwarz.jpg'
mv 'Julie Jarvis.png' 'julie-jarvis.png'
mv 'Juliet Connolly.jpg' 'juliet-connolly.jpg'
mv 'Karly Kang_0.png' 'karly-kang.png'
mv 'Katharine Lindley.jpg' 'katharine-lindley.jpg'
mv 'Katherine Ford.jpg' 'katherine-ford.jpg'
mv 'Kathryn Jenkins.jpg' 'kathryn-jenkins.jpg'
mv 'Kathy Bridges.jpg' 'kathy-bridges.jpg'
mv 'Keith Gordon.jpg' 'keith-gordon.jpg'
mv 'Liam Tanner.jpg' 'liam-tanner.jpg'
mv 'Magdalena Kaminska-Bunn.jpg' 'magdalena-kaminska-bunn.jpg'
mv 'Megan Saksida.jpg' 'megan-saksida.jpg'
mv 'Neil Tipping.jpg' 'neil-tipping.jpg'
mv 'Neil Warren.jpg' 'neil-warren.jpg'
mv 'Nicola Mullineux.png' 'nicola-mullineux.png'
mv 'Paul Howard.jpg' 'paul-howard.jpg'
mv 'Peter Herbert photo.png' 'peter-herbert-photo.png'
mv 'Phuong Nguyen.jpg' 'phuong-nguyen.jpg'
mv 'Sarah Baxendale  2.jpg' 'sarah-baxendale.jpg'
mv 'Sarah Bradford.jpg' 'sarah-bradford.jpg'
mv 'Sarah Kay 2 (002).jpg' 'sarah-kay.jpg'
mv 'Satwaki Chanda.jpg' 'satwaki-chanda.jpg'
mv 'Stephen Poole.jpg' 'stephen-poole.jpg'
mv 'Susan Singleton.jpg' 'susan-singleton.jpg'
mv 'Thomas Dalby.jpg' 'thomas-dalby.jpg'
mv 'Vicki Tydd.jpg' 'vicki-tydd.jpg'
mv 'Zigurds Kronbergs.jpg' 'zigurds-kronbergs.jpg'
mv 'Zoe Flude.jpg' 'zoe-flude.jpg'
mv 'alan_price.jpg' 'alan-price.jpg'
mv 'alistair_brown.jpg' 'alistair-brown.jpg'
mv 'allan-cinnamon.jpg' 'allan-cinnamon.jpg'
mv 'andrew-cockman.jpg' 'andrew-cockman.jpg'
mv 'andrew-green.jpg' 'andrew-green.jpg'
mv 'andy_willis.jpg' 'andy-willis.jpg'
mv 'angela-bedi.jpg' 'angela-bedi.jpg'
mv 'david_price.jpg' 'david-price.jpg'
mv 'edward_rands.jpg' 'edward-rands.jpg'
mv 'fiona_condron.jpg' 'fiona-condron.jpg'
mv 'glyn_fullelove_0.jpg' 'glyn-fullelove.jpg'
mv 'glynnis_carthy.jpg' 'glynnis-carthy.jpg'
mv 'helen_macneill.jpg' 'helen-macneill.jpg'
mv 'helena_wilkinson.jpg' 'helena-wilkinson.jpg'
mv 'john_selwood.jpg' 'john-selwood.jpg'
mv 'julia-clift.jpg' 'julia-clift.jpg'
mv 'julia_bowyer.jpg' 'julia-bowyer.jpg'
mv 'kate_palmer.jpg' 'kate-palmer.jpg'
mv 'laura-burrows.jpg' 'laura-burrows.jpg'
mv 'lesley-fidler.jpg' 'lesley-fidler.jpg'
mv 'liz_morris.jpg' 'liz-morris.jpg'
mv 'marek_muc.jpg' 'marek-muc.jpg'
mv 'martin-jackson.jpg' 'martin-jackson.jpg'
mv 'matt_tilling.jpg' 'matt-tilling.jpg'
mv 'ollie-garrod_0.jpg' 'ollie-garrod.jpg'
mv 'paul-davies.jpg' 'paul-davies.jpg'
mv 'paul-robbins.jpg' 'paul-robbins.jpg'
mv 'paul_coulam.jpg' 'paul-coulam.jpg'
mv 'paul_gee.jpg' 'paul-gee.jpg'
mv 'peter_rayney.jpg' 'peter-rayney.jpg'
mv 'phil-greatrex.jpg' 'phil-greatrex.jpg'
mv 'rachel_farris_0.jpg' 'rachel-farris.jpg'
mv 'richard-dew.jpg' 'richard-dew.jpg'
mv 'ritchie_tout.jpg' 'ritchie-tout.jpg'
mv 'rob_hobson.jpg' 'rob-hobson.jpg'
mv 'russell_corlett.jpg' 'russell-corlett.jpg'
mv 'samantha_tracey.jpg' 'samantha-tracey.jpg'
mv 'sarah_arnold.jpg' 'sarah-arnold.jpg'
mv 'sarah_laing.jpg' 'sarah-laing.jpg'
mv 'sharon_mckie.jpg' 'sharon-mckie.jpg'
mv 'simon_mckie.jpg' 'simon-mckie.jpg'
mv 'stephanie_webber.jpg' 'stephanie-webber.jpg'
mv 'stephen_relf.jpg' 'stephen-relf.jpg'
mv 'steve_collings.jpg' 'steve-collings.jpg'
mv 'tejashri-joshi.jpg' 'tejashri-joshi.jpg'
mv 'tim-palmer.jpg' 'tim-palmer.jpg'
mv 'vibul_wataranan.jpg' 'vibul-wataranan.jpg'

echo 'done';

ls -1
